#!python
# Copyright (c) 2023 Ivan Heibi.
#
# Permission to use, copy, modify, and/or distribute this software for any purpose
# with or without fee is hereby granted, provided that the above copyright notice
# and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
# DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
# ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
# SOFTWARE.
#
# v2.2
# New strategy to check unique citing entites
#
# v2.1
# Citations map could be created also using a CSV dump instead of Redis only
#
# v2
# A count of all unique citations is done to all the BRs (not only the ANYIDs that have multi OMIDs)

import csv
import argparse
from collections import defaultdict
from tqdm import tqdm
import re
import sys
import requests
from time import sleep
import json
import redis

# from zipfile import ZipFile
# import io

from oc.index.utils.logging import get_logger
from oc.index.utils.config import get_config

csv.field_size_limit(sys.maxsize)
config = get_config()
conf_br_ids = config.get("cnc", "br_ids").split(",")

'''
To create the omid map using the META BRs index (in CSV)
The META BRs index should be previously generated using 'meta2redis' command
'''
def read_omid_map(f_omidmap):
    global conf_br_ids

    omid_map = defaultdict(set)
    with open(f_omidmap, mode='r') as file:
        csv_reader = csv.reader(file)
        for row in csv_reader:
            if len(row) == 2:  # Ensure there are exactly two columns
                # ANY-ID:OMID 1:1
                # E.G openalex:W4375948413,omid:br/0634096064
                any_id, br_omid = row

                # also normalize omid val
                br_omid = br_omid.replace("omid:br/","")
                omid_map[br_omid].add(any_id)

    return omid_map

'''
Create the omid citations index using the omid citations index CSV file
The omid citations index CSV file should be previously generated using 'cits2redis' command
RETURNS:
    * omid_citations_index: {<CITED_OMID>: [<CITING_OMID_1>, <CITING_OMID_2>, ... <CITING_OMID_N>]}
'''
def read_omid_citations_index(f_omid_citations_index):

    omid_citations_index = defaultdict(list)
    with open(f_omid_citations_index, mode='r') as file:
        csv_reader = csv.reader(file)

        #TEST
        # csv_reader = csv_reader[:45000]

        for row in csv_reader:
            if len(row) == 2:  # Ensure there are exactly two columns
                cited_omid, str_citing_omids = row
                omid_citations_index[cited_omid] = str_citing_omids.split("; ")

    return omid_citations_index


def main():

    parser = argparse.ArgumentParser(description='Converts the citation count dump of OpenCitations Index based on BR OMIDs to any other ID (e.g., DOI, PMID)')
    parser.add_argument('--omidmap', required=True, help='Path to CSV dump containing the index/map of all BR in Meta (OMIDs) (*Note: generated by meta2redis)')
    # Data source in the format: <TYPE>:<VALUE>
    # E.G. REDIS:8 | CSV:/PATH/TO/OMID_CITAIONS_INDEX.csv
    parser.add_argument('--citations', default='redis:8', help='Either the Redis DB or CSV file storing all the citations of opencitations (*Note: populated by cits2redis). Specified in the form: <TYPE>:<VALUE>. E.G. REDIS:8 | CSV:/PATH/TO/OMID_CITAIONS_INDEX.csv')
    parser.add_argument('--id',  default='doi', help='Convert OMID(s) to a given ID')
    parser.add_argument('--out', default='./', help='Path to the output destination dir')
    args = parser.parse_args()
    logger = get_logger()

    # get ANYID Prefix. E:G. "doi"
    anyid_pref = args.id

    logger.info("Build a citation count for ANYID starting with the prefix: "+str(anyid_pref))

    # Build OMID map
    # FORMAT:
    #   <OMID>: SET(<anyid_pref>:<anyid_val>)
    # EXAMPLE:
    #   06804319241: {"doi:10.17615/3my7-0q76","pmid:18650518","pmid:18650512","doi:10.1056/nejme0804289","doi:10.1056/nejmoa0708975"}
    logger.info("Build OMID BR map ...")
    omid_map = read_omid_map(args.omidmap)
    logger.info("OMID MAP = "+str(len(omid_map.keys())))

    ds_cits_type, ds_cits_source = args.citations.lower().split(":")
    logger.info("Build OMID Cits map via "+ds_cits_type+" ...")
    if ds_cits_type == "redis":
        ds_cits_data = redis.Redis(host='localhost', port=6379, db=ds_cits_source)
    elif ds_cits_type == "csv":
        ds_cits_data = read_omid_citations_index(ds_cits_source)

    # Results to dump at the end
    anyid_citation_count = dict()
    anyid_map = defaultdict(set)

    # PARAMS
    CHUNCK_SIZE = 10000

    # (1) Walk through all OMIDS in the OMID map (i.e. omid_map)
    logger.info("Walk through all OMIDS in the OMID map (i.e. omid_map) ...")


    count_cits = {}
    for cited_omid, any_ids in tqdm(omid_map.items()):

        count_unique_cits = 0

        # calc cits count of the unique ANYIDS of each elem
        s_citing_omids = ds_cits_data.smembers(cited_omid)

        s_citing_unique_anyids = set()
        for citing_omid in s_citing_omids:
            citing_anyid = omid_map[citing_omid]
            if citing_anyid.isdisjoint(s_citing_unique_anyids):
                count_unique_cits += 1
            s_citing_unique_anyids.update(citing_anyid)

        # assign the count to each corresponding ANYID
        for __any_id in any_ids:
            count_cits[__any_id] = count_unique_cits

    # dump anyid - citation count
    logger.info('Saving the citation counts of '+anyid_pref+' BRs ...')
    with open(args.out+anyid_pref+"_citation_count.csv", mode='w', newline='') as output_csvfile:
        writer = csv.writer(output_csvfile)
        writer.writerow([anyid_pref, 'citation_count'])

        for cited_anyid, cit_count in count_cits.items():
            if cited_anyid.startswith(anyid_pref):
                writer.writerow([cited_anyid.replace(anyid_pref+":",""),str(cit_count)])

    logger.info("Done!")

#if __name__ == "__main__":
#    main()
